#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Deepslate Launcher executable runner."""
import os
import sys

_here = os.path.dirname(os.path.realpath(__file__))
if _here not in sys.path:
    sys.path.insert(0, _here)

from src.main import main

if __name__ == "__main__":
    main()
